### PR TITLE
Game Over: sound effects, click to restart, fix touch support

### LINKED ISSUE #91: New Game / Play Again
ensure state is refreshed, and an event is emitted so a front end can also refresh state. Probably should keep `bodyData` as source of play if game is lost. If game is won, maybe wait for new `bodyData`. Similarly add a updateState method, that the frontend could trigger, when there's a newer version of the game to play (like after a body was added). That way we can avoid these hard refreshes.

### PR DESCRIPTION
**Pull request by psugihara**
rn game over is a little anticlimactic. I feel like it should be more abrupt (pop!) and this helps.

Upon game over:
- Transition sound effect plays (will followup with some more spacy variations to check out)
- Songs 1, 2, 4 play at 2x speed, 3 goes to half speed
- Text "Click to play again" label

This also fixes mobile play which seems to have broken again and a small memory issue with unbinding click handlers.

fixes #91 

I'm including #95 because I wanted to hear/feel it all together but I will try more sound variation to the bubble based stuff, don't you worry @okwme.

### CODE REVIEW

**Comment by psugihara** [comment]
fixing conflicts

File: src/anybody.js [hunk 1]
```diff
@@ -169,32 +172,62 @@ export class Anybody extends EventEmitter {
   }
 
   addListener() {
-    // const body = document.getElementsByClassName('p5Canvas')[0]
-    const canvas = document.querySelector('canvas')
-    // const canvas = document.getElementById('defaultCanvas0')
+    const { canvas } = this
```
Comment (okwme) [inline src/anybody.js:183]: nice

File: src/sound.js [hunk 2]
```diff
@@ -216,26 +217,67 @@ export default class Sound {
...
     // play if it's been loaded or loads quickly, otherwise load and skip
     const now = Date.now()
     await loaded()
     if (Date.now() - now < 20) {
-      this.oneShots[url].start()
+      this.oneShots[key].start()
     }
   }
 
+  async playGameOver() {
```
Comment (okwme) [inline src/sound.js:252]: this is nice. in #94 I was getting frustrated trying to make it look smooth at the end when a body turns into a star and it made me realize we should probably just have a dedicated game over sequence where we do all of it rather than try to integrate it smoothly into game play. This function could be where it's expanded for more happening than just music.

File: src/visuals.js [hunk 3]
```diff
@@ -119,16 +120,18 @@ export const Visuals = {
     } else {
       this.justPaused = false
     }
-    if (this.frames - this.startingFrame >= this.timer) {
+    if (this.frames - this.startingFrame + FPS >= this.timer) {
```
Comment (okwme) [inline src/visuals.js:278]: so this waits a full second until the ending starts? Is that just for better rhythm?

File: src/visuals.js [hunk 4]
```diff
@@ -525,21 +535,30 @@ export const Visuals = {
   },
 
   drawExplosions() {
-    if (this.explosions.length > 0) {
-      for (let i = 0; i < this.explosions.length; i++) {
-        const bomb = this.explosions[i][0]
+    const { p, explosions } = this
```
Comment (okwme) [inline src/visuals.js:746]: nice

**Review by okwme — APPROVED** [review]

**Comment by okwme** [comment]
LGTM @psugihara you wanna merge?

File: src/visuals.js (hunk 3 above)
Comment (psugihara) [reply src/visuals.js:278]: this ends the game after 1 rather than 0.

3, 2, 1, GAME OVER

rather than

3, 2, 1, 0, GAME OVER

not married to it

**Comment by okwme** [comment]
oops, actually i'm getting an error when i run it

**Comment by okwme** [comment]
```
canvas.removeEventListener is not a function
    at Anybody.addListener (anybody.js:196:14)
    at Anybody.start (anybody.js:116:10)
```

**Comment by psugihara** [comment]
hm dang maybe bad merge

**Comment by okwme** [comment]
think i got it @psugihara, the canvas object is actually a p5instance object so canvas is accessed by canvas.canvas

**Comment by psugihara** [comment]
ah. i think we could switch to just using this.p.canvas

weirdly i don't see this error at all on my end.

**Comment by psugihara** [comment]
lemme switch to that quick

**Comment by okwme** [comment]
oh true, i just tried renaming to p5instance but you're right this.p.canvas would work better

**Comment by psugihara** [comment]
Screenshot 2024-04-08 at 1 50 41 PM

little bug, text stays big after game over. fixing
